# Mandatory name of group to compute the path for
string group_name
string end_effector_link

string[] joint_names
JointPathPoint[] points

---

# The computed solution trajectory, for the desired group, in configuration space
geometry_msgs/PoseStamped[] solutions

# The error code of the computation
moveit_msgs/MoveItErrorCodes[] error_codes

string[] error_msgs