trajectory_msgs/JointTrajectoryPoint[] waypoints #last waypoint is alwas the goal
float64[] velocities_constraints
float64[] accelerations_constraints
std_msgs/String group_name
---
#result definition
int32 result
---
#feedback
bool isconverged
